Update xdebug_info() CSS to make table headers sticky
xdebug/xdebug pull request #678
Opened 2020-10-29 16:27 UTC by Ayesh

Hi Derick,
Long time fan, first time PR sender :)

A small suggestion to make the table headers of the xdebug_info HTML display sticky, as in the table headers stay on the top of the browser page, while the user scrolls. PHP core `phpinfo` already has them, and I think xdebug could follow suit. 

![image](https://user-images.githubusercontent.com/811553/97602613-1787c380-1a3e-11eb-8e57-cc1aaf39f1ae.png)

Thank you.

2020-10-30 11:33 UTC, derickr commented
I like the idea of this, but I looks like this change makes the black borders not show up on the right and bottom sides of the header any more:

![Missing Borders](http://derickrethans.nl/files/dump/borders-cut-off.png)

2020-10-30 11:34 UTC, derickr requested changes
Please have a look at whether you can make the borders work too.

2020-11-02 07:52 UTC, Ayesh commented
Thanks a lot for your review, @derickr - You are right the borders look messy in Firefox. This is a Firefox [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1450584), that's not present in Chromium. `phpinfo()` table also has this table background bleed issue on Firefox. 

I went probably a little overboard with this, but I could make them work by making the browser draw all the borders, and selectively turning them off in sides to prevent overlaps. The result look good in all browsers. 

![image](https://user-images.githubusercontent.com/811553/97842574-64a7b600-1d1a-11eb-9f94-9709ef58113d.png)

I totally understand if you'd rather not have these extra CSS  for a sticky table for the sake of simplicity.
Thank you.

2020-11-18 15:53 UTC, derickr commented
I've merged this after a rebase and a white space fix. It will make it into Xdebgu 3.0.0. Thanks for your PR!

2020-11-18 15:53 UTC, closed without merging