Expose __EXCEPTION virtual variable for current EG(exception)
xdebug/xdebug pull request #922
Opened 2023-11-16 14:12 UTC by zobo

This could be a way to expose the current Exception that is in EG(exception). I have tested this with VSC and it does indeed work.

![image](https://github.com/xdebug/xdebug/assets/2456026/28b547b1-6cc1-48e4-a82b-76dbd87266a2)

However, I think a better way would be to provide a _dynamic_ context name when an exception is available.. Same with return value. Maybe....

I have not written any tests for this yet.

2023-11-24 12:13 UTC, derickr commented
I think I'm generally OK with this, but it confuses me that tests on Windows are not failing, whereas there is a test (I think rightfully) failing on Linux. And of course, we need tests :-)

2024-03-22 12:00 UTC, derickr requested changes
I think this should be guarded by a feature set, as we discussed in our meeting. The reason is that otherwise IDEs could suddenly see this extra virtual variable, without knowing why. 

The PR should also add tests to check whether this new feature works. I don't think we should *not* fix the currently failing test, as it has not opted in into this new behaviour.

2024-03-26 02:52 UTC, zobo commented on src/debugger/handler_dbgp.c
> +	if (EG(exception) && depth == 0) {
Added comment and feature flag.

2024-03-26 03:29 UTC, zobo commented on src/debugger/handler_dbgp.c
> +		xdebug_xml_expand_attribute_value(tmp_node, "facet", "readonly virtual");
Can't find a use for it right now since I can use the name to check ... but could add it later if needed.

2025-04-11 14:33 UTC, derickr commented
Merged this after a rebase, so closing by hand.

2025-04-11 14:33 UTC, closed without merging